// Todays words
export const GET_TODAYS_WORDS = 'GET_TODAYS_WORDS';
export const EDIT_TODAYS_WORDS = 'EDIT_TODAYS_WORDS';
export const SET_IS_CORRECT = 'SET_IS_CORRECT';
export const SET_IS_ANSWERED_TO_TRUE = 'SET_IS_ANSWERED_TO_TRUE';
export const UPDATE_TODAYS_WORDS_IN_DB = 'UPDATE_TODAYS_WORDS_IN_DB';

// User words
export const WORD_ADDED = 'WORD_ADDED';
export const FAILED_TO_ADD_WORD = 'FAILED_TO_ADD_WORD';
export const GET_WORDS = 'GET_WORDS';
export const WORDS_FETCH_SUCCESSFULL = 'WORDS_FETCH_SUCCESSFULL';
export const WORDS_FETCH_FAILED = 'WORDS_FETCH_FAILED';
export const DELETE_WORD = 'DELETE_WORD';
export const WORD_DELETED = 'WORD_DELETED';
export const WORD_UPDATED = 'WORD_UPDATED';

// Authetication
export const USER_LOADING = 'USER_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const TOKEN_AUTHENTICATION_FAILED = 'TOKEN_AUTHENTICATION_FAILED';
export const TOKEN_AUTHENTICATION_SUCCESS = 'TOKEN_AUTHENTICATION_SUCCESS';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';